/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{js,jsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary-fixed-dim': '#b7cdac',
        'on-secondary-fixed': '#351000',
        primary: '#384b32',
        'surface-tint': '#506449',
        'secondary-container': '#fe9a6a',
        'on-secondary': '#ffffff',
        'on-surface': '#1c1c18',
        'inverse-on-surface': '#f3f0ea',
        surface: '#fcf9f3',
        'primary-fixed': '#d2e9c7',
        'on-tertiary-fixed-variant': '#3c4b38',
        'surface-variant': '#e5e2dc',
        'error-container': '#ffdad6',
        'outline-variant': '#c4c8be',
        'on-secondary-container': '#763007',
        'on-background': '#1c1c18',
        'secondary-fixed-dim': '#ffb694',
        outline: '#747870',
        'on-primary-fixed': '#0e200a',
        'on-tertiary-fixed': '#121f10',
        'surface-bright': '#fcf9f3',
        background: '#fcf9f3',
        'on-secondary-fixed-variant': '#783108',
        tertiary: '#3c4a38',
        'on-primary-container': '#c7debc',
        'on-error-container': '#93000a',
        'surface-container-highest': '#e5e2dc',
        'on-error': '#ffffff',
        'on-tertiary-container': '#ccddc4',
        'surface-container-low': '#f6f3ed',
        'tertiary-fixed': '#d7e7cf',
        'surface-container-high': '#ebe8e2',
        'tertiary-fixed-dim': '#bbcbb3',
        error: '#ba1a1a',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#53624f',
        'on-primary': '#ffffff',
        'secondary-fixed': '#ffdbcc',
        'surface-container': '#f0eee8',
        secondary: '#96481f',
        'on-surface-variant': '#444840',
        'surface-container-lowest': '#ffffff',
        'on-primary-fixed-variant': '#394c33',
        'inverse-surface': '#31312d',
        'inverse-primary': '#b7cdac',
        'primary-container': '#4f6348',
        'surface-dim': '#dcdad4',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        gutter: '16px',
        lg: '24px',
        sm: '8px',
        'margin-desktop': '64px',
        unit: '4px',
        'margin-mobile': '20px',
        xl: '40px',
        md: '16px',
        xs: '4px',
      },
      fontFamily: {
        'label-sm': ['Work Sans', 'sans-serif'],
        'body-lg': ['Work Sans', 'sans-serif'],
        'headline-xl': ['Epilogue', 'sans-serif'],
        'headline-lg-mobile': ['Epilogue', 'sans-serif'],
        'headline-md': ['Epilogue', 'sans-serif'],
        'body-md': ['Work Sans', 'sans-serif'],
        'headline-lg': ['Epilogue', 'sans-serif'],
        'label-md': ['Work Sans', 'sans-serif'],
      },
      fontSize: {
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '34px', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
